INSERT INTO anubhav_db_master_address (
    NODE_KEY,
    CITY,
    POSTAL_CODE,
    STREET,
    BUILDING,
    COUNTRY,
    ADDRESS_TYPE,
    VAL_START_DATE,
    VAL_END_DATE,
    LATITUDE,
    LONGITUDE
  )
VALUES (
    'NODE_KEY:NVARCHAR(32)',
    'CITY:NVARCHAR(44)',
    'POSTAL_CODE:NVARCHAR(8)',
    'STREET:NVARCHAR(44)',
    'BUILDING:NVARCHAR(128)',
    'COUNTRY:NVARCHAR(44)',
    'ADDRESS_TYPE:NVARCHAR(44)',
    'VAL_START_DATE:DATE_TEXT',
    'VAL_END_DATE:DATE_TEXT',
    'LATITUDE:DECIMAL',
    'LONGITUDE:DECIMAL'
  );